trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo Installing Node.js...
    curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
    sudo apt-get install -y nodejs
  displayName: 'Install Node.js'

- script: |
    echo Installing dependencies...
    npm install
  displayName: 'Install dependencies'

- script: |
    echo Running tests...
    npm test
  displayName: 'Run tests'

- script: |
    echo Building project...
    npm run build
  displayName: 'Build project'